### ISSUE TITLE
Using different maps

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#10]
What is the source of the JSON file "ne_110m_admin_0_countries.json" this project uses for it's maps?  Is it  [Natrual Earth Data](http://www.naturalearthdata.com/downloads/110m-cultural-vectors/)? If yes, how do you convert their download-able data sets into the JSON this project uses?

We're looking to do things like render a map with out Antarctica and as well be aware of on going conflicts with boundries in somali/somaliland and morocco/western sahara.  For example,in somali/somaliland most political maps don't list a "formal border" between the two countries, but the base map here, does.  

I suspect this exposes how much of a map/json/svg newbie I am ;)

**Comment by melalj** [comment]
I have made public a script to generate such dataset:
https://github.com/melalj/topojson-map-generator

Check its Makefile and see how we can skip Antartica. I'm not sure about the borders but it should be a way to do it.

**Comment by Ths2-9Y-LqJt6** [comment]
Works for me!  I'll close this ticket and follow up on the topojson-map-generator repo as needed.  Thanks!
