### ISSUE TITLE
Scrolling up when we click on New filter

### ISSUE THREAD

**Issue by melalj** [Packet-Clearing-House/maptable#20]
There's a little fix:

on https://github.com/Packet-Clearing-House/maptable/blob/master/src/components/Filters.js#L72
```js
add() {
```

You'll need to prevent the default behavior of the <a href=#"> tag on click.
```js
add(evt) {
    evt.preventDefault();
```

**Comment by Ths2-9Y-LqJt6** [comment]
it works! i'll do a PR

**Comment by Ths2-9Y-LqJt6** [comment]
fixed with PR #21
