### ISSUE TITLE
Pass raw data to map.countries.attr.fill.transform()

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#34]
If you want to have your countries have a colors based on percentile, or other relative values to the dataset, you need to do a comparative call on the specific `val` in `map.countries.attr.fill.transform()` to all the other values.  Right now, you can only transform the `val` based math calls like `Math.sqrt(val)`.  

The solution is a one line change (well and a bit more to tidy up the docs), just pass `this.maptable.rawData` in on line [476 of GeoMap.js](https://github.com/Packet-Clearing-House/maptable/blob/master/src/components/GeoMap.js#L476)

**Comment by melalj** [comment]
Fixed on #35 and #43
