### ISSUE TITLE
clicking "+ New filter": markers and marker borders swell when zoomed

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#41]
## Overview

when you have a map with markers for lat long cordinates and you zoom in and then click "+ New Filter" the markers swell, getting bigger and the stroke gets bigger too.

## version 1
steps to reproduce
1. go to https://bl.ocks.org/melalj/cc130ad4072a2f52a5aa
1. zoom in on a maker as far as you can
1. click "+New Filter"

**expected**: markers and marker borders don't change size or stroke
**actual**: markers swell bigger and the stroke increases
work around: filter zoomed all the way out, then zoom in.  or zoom back or zoom in (if avail) one level after filtering and zoom back in.

## version 2
steps to reproduce
1. go to https://bl.ocks.org/melalj/cc130ad4072a2f52a5aa
1. click "+New Filter"
1. zoom in on a maker as far as you can
1. click "-Remove Filter"

**expected**: markers and marker borders don't change size or stroke
**actual**: markers swell bigger and the stroke increases
work around: filter zoomed all the way out, then zoom in.  or zoom back or zoom in (if avail)  one level after removing filter and zoom back in.

**Comment by melalj** [comment]
Fixed on #46
