### ISSUE TITLE
renctangles show around markers when zoomed in in safari

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#45]
steps to reproduce:
1.  open safari
1.  go to https://bl.ocks.org/melalj/cc130ad4072a2f52a5aa
1.  zoom all the way in to italy

expected: markers show as circles
actual: markers show as circles with squares around
work arounds: use chrome or ff. don't zoom so far in when using safari

![squares around markers](https://cloud.githubusercontent.com/assets/8253488/21244415/5f608704-c2d2-11e6-9832-6a195e1f3d97.png)

**Comment by melalj** [comment]
Cannot reproduce it on Safari 9.1.2.

**Comment by Ths2-9Y-LqJt6** [comment]
I'm using MacOS 10.12.1 with Safari 10.0.1

**Comment by melalj** [comment]
Tried it on MacOS 10.13.1 with Safari 11.0.1 and couldn't reproduce it.
<img width="636" alt="screenshot 2018-07-12 17 48 46" src="https://user-images.githubusercontent.com/3869766/42666769-ea926b56-85fb-11e8-85c2-07ce3bf43abc.png">

**Comment by Ths2-9Y-LqJt6** [comment]
ok - let's close for now and if woody complains again we'll re-open
