### ISSUE TITLE
some throws are uncaught

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#5]
in the current [refactor branch](https://github.com/Packet-Clearing-House/maptable/blob/5be65d0a4e22db18e18d1377c4ae3b95b925d353/build/maptable.js) when line 671 is hit and `!attrValue.rollup` is true:

```javascript
if (!attrValue.rollup) {
  throw new Error('MapTable: rollup property is not defined for attr.' + attrKey);
}
```

nothing catches that and so we get the a JS error:

`Uncaught Error: MapTable: rollup property is not defined for attr.r`

I suspect lines 675, 706 and possibly 718 will suffer the same problem

**Comment by Ths2-9Y-LqJt6** [comment]
Aha - so my being a total JS newbie may be shining through here - it may be common to do a `throw` outside of a `try/catch`.  If that's the case, then this can largely be ignored!

if this can be ignored, then the only feedback is that I'd give the full context of where the `attr.r` is missing from so it's easier to chase down.  In this case it's `map.markers.attr.r.rollup()`

**Comment by melalj** [comment]
I added a default value for rollup:
https://github.com/Packet-Clearing-House/maptable/pull/4/commits/c3c9e10dd8d21c708cb3398b75ebc775b9a7d152
