### ISSUE TITLE
heatmap and filter problems

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#53]
for this ticket, set up a heatmap with filters enabled with  maptable 1.4.0. testing was done on FF and chromium. i started with [this bl.ocks.org](https://bl.ocks.org/melalj/raw/145ef67aa04a6713bc1d026eed46c59e) and added `filters()`

**note**: upon closer inspection, both items below seem to show identical behavior  (heatmap grows ever larger)

## heatmap changes when clicking "remove" or "new"
steps to reproduce:
1. create a heatmap with filters enabled
1. click "New Filter"
expected: map is unchanged and new filter options are shown
actual: heatmap grows larger and new filter options are shown
work around: don't use filters or reload page
note: the same is true for when you click "Remove this Filter"

## heatmap doesn't update correctly when you add a filter
1. create a heatmap with filters enabled
1. click "New Filter"
1. add the filter by adding filter parameters 
expected: map is filtered and heatmap updates accordingly based on filtered markers
actual: heatmap grows larger and markers are filtered

**Comment by melalj** [comment]
Fixed with #61
