### ISSUE TITLE
change the way colors work in heatmap

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#56]
In a heatmap, right now, if you specify a color like this: ``heatmap.circles.color = '#043864'`` the starting color (area with most overlaps) ends up being not ``#043864``, but instead it is lighter. As well, on the way from the darkest color to white, maptable chooses it's own transition colors used in the gradient.  You should be able to specify which colors it transitions through.  Specifically, PCH would like a way for the darkest color on any heatmap to always start at ``heatmap.circles.color``and for the colors on the way to white be the ones we use in our palette.  Currently we define our palette with a min an max which works great on the choropleth maps [like this one](https://www.pch.net/ixp/summary). We'd like the same for the heatmap.

**Comment by Ths2-9Y-LqJt6** [comment]
@melalj  - looking really close!  The colors do fall off accurately I think, matching what I'd expect to see.  The darkest color in Europe doesn't quite match the darkest color (aka 100%) in our [existing percentile based choropleth map](https://www.pch.net/ixp/summary_growth_by_country) (see US).

**Comment by melalj** [comment]
We Should not close the issue, before it the PR is closed and merged to master ;)
I added comments on the PR

**Comment by Ths2-9Y-LqJt6** [comment]
looks good - thanks @melalj also - didn't mean to close the issue last time, thanks for re-opening.
