### ISSUE TITLE
map doesn't resize on window resize

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#6]
When I render mapTable in a relative small browser window and then resize the window to make it the map and table bigger, the map stays the size it was originally rendered at. Here's a screenshot from the "00 - Basic" example code:

![un resized map](https://cloud.githubusercontent.com/assets/8253488/14034130/881902aa-f1dd-11e5-9425-cd00d5951f6e.png)

**Comment by melalj** [comment]
Good catch!
Fixed here : https://github.com/Packet-Clearing-House/maptable/pull/4/commits/74479bc14c7d5bd156be7e4799c7985eea76df3b
