### ISSUE TITLE
MapTable doesn't work in IE11

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#7]
Heya! I think we decided that <IE11 won't be supported.  However, none of the demos hosted on blocks.org (eg [Basic Map - Custom markers](https://bl.ocks.org/melalj/2394323e478dca231128)) work in modern.ie's latest [IE11 VM](https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/).

**Comment by melalj** [comment]
I just tried it [on BrowserStack](https://www.browserstack.com/start#os=Windows&os_version=10&browser=IE&browser_version=11.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&url=https%3A%2F%2Fbl.ocks.org%2Fmelalj%2Fraw%2F772c8a846a3f308e9358%2Fb8b39512d91b56ce4383cfd5a491083ff3f1b42f%2F&speed=1&host_ports=google.com%2C80%2C0):

I get this error: `SCRIPT65535: Invalid calling object`  (seriously Microsoft... :unamused:)

Will dive more on this later

**Comment by Ths2-9Y-LqJt6** [comment]
Hey @melalj  - You have some time in the next couple of days to bang on this?  Be handy for an internal PCH deadline if it was fixed, but only if it's convenient for you.  

[POSE](http://stackoverflow.com/questions/14581936/error-script65535-invalid-calling-object-line-1-character-1)?

Thanks!

**Comment by Ths2-9Y-LqJt6** [comment]
Never mind!  No rush on this now.  We'll need it some day, but not just yet.  Thanks!

**Comment by melalj** [comment]
The link that you provided is very specific to his use case. There's no onLoad attribute in MapTable.
I'm not very familiar with the debugging tools of IE.

**Comment by Ths2-9Y-LqJt6** [comment]
Hey again!  PCH has prioritized deploying maptable on our [IXP Dir home page](https://prefix.pch.net/applications/ixpdir/).  There's no rush on this!  We'll be spinning up an Windows VM with IE to dive into this henceforth.

**Comment by Ths2-9Y-LqJt6** [comment]
progress!  i ran ie11 against the non-minified version.  The line it's having problems with ``if (toString.call(src) === '[object Object]') {`` in the ``extendRecursive`` function:

```javascript
  function extendRecursive() {
    var dst = {};
    var src = void 0;
    var p = void 0;
    var args = [].splice.call(arguments, 0);

    while (args.length > 0) {
      src = args.splice(0, 1)[0];
      if (toString.call(src) === '[object Object]') {
        for (p in src) {
          if (src.hasOwnProperty(p)) {
            if (toString.call(src[p]) === '[object Object]') {
              dst[p] = extendRecursive(dst[p] || {}, src[p]);
            } else {
              dst[p] = src[p];
            }
          }
        }
      }
    }
    return dst;
  }
```

 so, armed with that detail, it looks like [this stack exchange post](http://stackoverflow.com/questions/19321938/invalid-calling-object-error-in-ie) might be the answer: 


> You seem to be neglecting the fact
> 
> `window.toString === Object.prototype.toString; // false`
> 
> The Window's toString is implementation-specific and there is nothing in the specification saying methods on DOM Host Objects have to work with call/on other objects/etc
> 
> If you want to capture this toString but can't assume prototype, try
> 
> `var toString = ({}).toString;`
> `toString.call({}); // "[object Object]"`

i'll dive in and see if there's not a fix somewhere in here!

**Comment by melalj** [comment]
Change this line:

https://github.com/Packet-Clearing-House/maptable/blob/master/src/components/Table.js#L41
```
      .data(this.activeColumns.map(k => Object.assign({ key: k }, this.maptable.columnDetails[k])))
```

to:
```
      .data(this.activeColumns.map(k => utils.extendRecursive({ key: k }, this.maptable.columnDetails[k])))
```

**Comment by Ths2-9Y-LqJt6** [comment]
yay!  adding ``var toString = ({}).toString;`` to the [``extendRecursive()``](https://github.com/Packet-Clearing-House/maptable/blob/master/dist/maptable.js#L71) function and then making your recommended [change to table.js](https://github.com/Packet-Clearing-House/maptable/blob/master/src/components/Table.js#L41) per above, totally makes it render correctly in IE ! 

However now, see the filters don't work :( .  The error is in [``getPossibleFilters(), line 297``](https://github.com/Packet-Clearing-House/maptable/blob/master/src/components/Filters.js#L297):

```
Object doesn't support property or method 'assign'
```

I'm diving into it now!

**Comment by melalj** [comment]
https://github.com/Packet-Clearing-House/maptable/blob/dev-11/src/components/Filters.js#L297

Same here, replace `Object.assign` with `utils.extendRecursive`

**Comment by Ths2-9Y-LqJt6** [comment]
yay! that did it.  now if I can just figure how to commit the changes.  see [my comment](https://github.com/Packet-Clearing-House/maptable/issues/11#issuecomment-227839189) on #11

**Comment by Ths2-9Y-LqJt6** [comment]
next up!  Clicking "remove filter" results in an error on [line 99 of ``remove()``](https://github.com/Packet-Clearing-House/maptable/blob/master/src/components/Filters.js#L98):

```
Object doesn't support property or method 'remove'
```

Line 98 is:

```
if (rowNode) rowNode.remove();
```

**Comment by melalj** [comment]
you can use this:
`rowNode.parentNode.removeChild(rowNode);` instead of `rowNode.remove()`
