### ISSUE TITLE
error when using first column as defaultSorting

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#71]
if you have a ``table()`` section on your maptable that has a ``defaultSorting`` which references the first column of csv data, you get an error:

``TypeError: d3.event is null      Table.js:206:11``

This references this if statement:

```javascript
if (!d3.event.shiftKey) {
    this.sorting = [this.sorting[sortIndex]];
}
```

To reproduce, change ``city`` to ``country`` in the [default.sort.html](https://github.com/Packet-Clearing-House/maptable/blob/cbd576cac66d6dc18e97ed2a3c0a6d63776b657b/examples/default.sort.html#L23) example:

```javascript
defaultSorting: {
    key: "country"
}
```

current work around is re-order the data source to not have first column be the one you want to sort on

**Comment by melalj** [comment]
@Ths2-9Y-LqJt6 Should be fixed with #81 !
