### ISSUE TITLE
Examples: JS errors, padding, need MapTable 1.6.0 

### ISSUE THREAD

**Issue by Ths2-9Y-LqJt6** [Packet-Clearing-House/maptable#86]
The examples need some love!

### Error
First and foremost, this one doesn't work:

MapTable: Only Table and filters - sorting, virtual columns
https://bl.ocks.org/melalj/ef85eb677583647daf52

it gets an error:

```
maptable.min.js:2 Uncaught TypeError: Cannot set property 'heatmap' of null
    at Object.a.render (maptable.min.js:2)
    at (index):51
```
### Upgrade
All of them  need to be upgraded to maptable 1.6.0

### Padding

* This one](https://bl.ocks.org/melalj/2394323e478dca231128) has a huge ocean underneath Antarctica when it shouldn't:  [huge ocean](https://user-images.githubusercontent.com/8253488/43917759-038047ac-9bc6-11e8-8c42-d1f432b00c55.png)
* [This one has](http://bl.ocks.org/melalj/772c8a846a3f308e9358) a similar issue, but there's no ocean, just white space: [whitespace 1](https://user-images.githubusercontent.com/8253488/43917768-093dacc0-9bc6-11e8-95cb-ca2844355216.png)
* [This one has](https://bl.ocks.org/melalj/07be61a538509b8e4a7e) a space above: [space above](https://user-images.githubusercontent.com/8253488/43917913-69f17f9c-9bc6-11e8-9a04-c3412a7bf32c.png)
* [This one](https://bl.ocks.org/melalj/1aa4dd90b4561deb8de6) also has a space below: [space2](https://user-images.githubusercontent.com/8253488/43917964-88a137b6-9bc6-11e8-8bf1-c6583985719a.png)
* [This one ](https://bl.ocks.org/melalj/145ef67aa04a6713bc1d026eed46c59e)has also also has a space below: [space3](https://user-images.githubusercontent.com/8253488/43918004-a2853d1c-9bc6-11e8-9b67-e5e2c6de6cb8.png)

All screenshots taken on Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by melalj** [comment]
Should be solved on 1.6.1 with #36
